// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SaidaPessoas.API.Data;

#nullable disable

namespace SaidaPessoas.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SaidaPessoas.API.Models.SolicitacaoSaida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAprovacaoGestor")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DataAprovacaoRH")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DataPrevistaRetorno")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("GestorAprovadorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("HoraRetorno")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("HoraSaida")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("HorarioPrevistodoRetorno")
                        .HasColumnType("text");

                    b.Property<bool>("IsExtraordinaria")
                        .HasColumnType("boolean");

                    b.Property<string>("MotivoReprovacao")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeVigilante")
                        .HasColumnType("text");

                    b.Property<bool>("PrevisaoRetorno")
                        .HasColumnType("boolean");

                    b.Property<int?>("RHAprovadorId")
                        .HasColumnType("integer");

                    b.Property<string>("Setor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SetorDestino")
                        .HasColumnType("text");

                    b.Property<int>("SolicitanteId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoSaida")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UnidadeDestino")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SolicitanteId");

                    b.ToTable("Solicitacoes");
                });

            modelBuilder.Entity("SaidaPessoas.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Setor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Matricula")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SaidaPessoas.API.Models.SolicitacaoSaida", b =>
                {
                    b.HasOne("SaidaPessoas.API.Models.Usuario", "Solicitante")
                        .WithMany("Solicitacoes")
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Solicitante");
                });

            modelBuilder.Entity("SaidaPessoas.API.Models.Usuario", b =>
                {
                    b.Navigation("Solicitacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
