/** Setores de usuário disponíveis no cadastro e na administração. */
export const SETORES_USUARIO = ['TIC', 'DEPOTS'] as const;

/** Unidades do sistema e seus setores internos (usado no destino de saídas a serviço). */
export const UNIDADES_SETORES: Record<string, string[]> = {
  ALFANDEGADO: [
    'DIRETORIA', 'COMERCIAL', 'AVERBAÇÃO', 'CONTROLADORIA', 'FATURAMENTO',
    'SGQ', 'FALTAS E AVARIAS', 'FROTA', 'PATIO', 'PIER', 'PCO', 'AMBIENTAL',
    'LOGISTICA', 'GATES', 'TI', 'ARMAZEM', 'ENTREPOSTO', 'MANUTENÇÃO DE PESADOS',
    'NAVEGAÇÃO', 'MAPA', 'RH', 'GRC', 'BOLSÃO', 'PORTARIA 3', 'PORTARIA 2',
    'SESMT', 'AMBULATÓRIO',
    'PORTARIA 1', 'PORTARIA 4', 'PORTARIA 5', 'PORTARIA 6', 'PORTARIA RIO NEGRO',
  ],
  ATR: [
    'RECEPÇÃO', 'GESTÃO', 'PCO', 'TERMINAL', 'BALANÇA', 'FROTA', 'GATE',
    'MANUTENÇÃO', 'SESMT', 'RH', 'FATURAMENTO', 'ARMAZÉM', 'DESEMBARQUE',
  ],
  TOMIASI: [
    'RECEPÇÃO', 'GERÊNCIA', 'REMOÇÃO', 'COMERCIAL', 'GATE', 'OFICINA DE AUTOS',
    'ABASTECIMENTO', 'TI INFORMÁTICA', 'RH BASE', 'SESMT/AMBULATÓRIO',
  ],
  RETROPORTO: [
    'PRESIDENCIA', 'DIRETORIA FINANCEIRA', 'AMBIENTAL', 'DOCUMENTAÇÃO PORTUÁRIA',
    'AREA FINANCEIRA', 'COBRANÇA', 'CONTAS A RECEBER/CAIXA', 'CONTABILIDADE',
    'CONTAS A PAGAR', 'CONTROLADORIA', 'FATURAMENTO', 'CONTABILIDADE RETROPORTO',
    'JURIDICO TRABALHISTA', 'RH', 'RECEPÇÃO PRESIDENCIAL', 'COMERCIAL', 'FISCAL',
    'TI RETROPORTO', 'SUPRIMENTOS - COMPRAS', 'ARMAZEM', 'JURIDICO CIVIL',
    'CSC/DAL', 'GRC', 'SESMT', 'AMBULATORIO', 'RECEPÇÃO RETROPORTO', 'TELEFONIA',
    'GESTÃO DE COMPETENCIA', 'COPA DIRETORIA', 'SUPORTE TOTVS/AUDITORIA',
  ],
};

/** Nomes das unidades do sistema (chaves de UNIDADES_SETORES). */
export const UNIDADES = Object.keys(UNIDADES_SETORES);
